---
- Bye
- Bye-bye
- Catch you later
- Farewell
- Goodbye
- Happy trails
- Later
- Later alligator
- Peace
- Peace out
- See ya
- See you around
- See you later
- See you soon
- So long
- Take care
- Till next time
