---
- Awesome
- Amazing
- Amazeballs
- Bam
- Bingo
- Boom
- Booyah
- Cha-ching
- Congrats
- Cowabunga
- Fantastic
- Great
- Hot diggety
- Hooray
- Nice
- Niiiiice
- Nice one
- Right on
- Well done
- w00t
- Woo
- Yay
- Yeah
- Yippee
- Zowie